// flow-typed signature: e453e27b063a88cdf7a0e4f55d355f6e
// flow-typed version: <<STUB>>/app-root-dir_v^1.0.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'app-root-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'app-root-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'app-root-dir/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'app-root-dir/lib/index' {
  declare module.exports: $Exports<'app-root-dir/lib'>;
}
declare module 'app-root-dir/lib/index.js' {
  declare module.exports: $Exports<'app-root-dir/lib'>;
}
