// flow-typed signature: a1af4008af0e62af70d84e517522a54c
// flow-typed version: <<STUB>>/config_v^3.2.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'config/async' {
  declare module.exports: any;
}

declare module 'config/defer' {
  declare module.exports: any;
}

declare module 'config/lib/config' {
  declare module.exports: any;
}

declare module 'config/parser' {
  declare module.exports: any;
}

declare module 'config/raw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'config/async.js' {
  declare module.exports: $Exports<'config/async'>;
}
declare module 'config/defer.js' {
  declare module.exports: $Exports<'config/defer'>;
}
declare module 'config/lib/config.js' {
  declare module.exports: $Exports<'config/lib/config'>;
}
declare module 'config/parser.js' {
  declare module.exports: $Exports<'config/parser'>;
}
declare module 'config/raw.js' {
  declare module.exports: $Exports<'config/raw'>;
}
