// flow-typed signature: dd9819deb081b65d2d4086b548ad58ee
// flow-typed version: <<STUB>>/dyson_v^2.0.5/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dyson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dyson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dyson/bin/dyson' {
  declare module.exports: any;
}

declare module 'dyson/lib/defaults' {
  declare module.exports: any;
}

declare module 'dyson/lib/delay' {
  declare module.exports: any;
}

declare module 'dyson/lib/dyson' {
  declare module.exports: any;
}

declare module 'dyson/lib/loader' {
  declare module.exports: any;
}

declare module 'dyson/lib/multiRequest' {
  declare module.exports: any;
}

declare module 'dyson/lib/parameter' {
  declare module.exports: any;
}

declare module 'dyson/lib/proxy' {
  declare module.exports: any;
}

declare module 'dyson/lib/raw-body' {
  declare module.exports: any;
}

declare module 'dyson/lib/response' {
  declare module.exports: any;
}

declare module 'dyson/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dyson/bin/dyson.js' {
  declare module.exports: $Exports<'dyson/bin/dyson'>;
}
declare module 'dyson/lib/defaults.js' {
  declare module.exports: $Exports<'dyson/lib/defaults'>;
}
declare module 'dyson/lib/delay.js' {
  declare module.exports: $Exports<'dyson/lib/delay'>;
}
declare module 'dyson/lib/dyson.js' {
  declare module.exports: $Exports<'dyson/lib/dyson'>;
}
declare module 'dyson/lib/loader.js' {
  declare module.exports: $Exports<'dyson/lib/loader'>;
}
declare module 'dyson/lib/multiRequest.js' {
  declare module.exports: $Exports<'dyson/lib/multiRequest'>;
}
declare module 'dyson/lib/parameter.js' {
  declare module.exports: $Exports<'dyson/lib/parameter'>;
}
declare module 'dyson/lib/proxy.js' {
  declare module.exports: $Exports<'dyson/lib/proxy'>;
}
declare module 'dyson/lib/raw-body.js' {
  declare module.exports: $Exports<'dyson/lib/raw-body'>;
}
declare module 'dyson/lib/response.js' {
  declare module.exports: $Exports<'dyson/lib/response'>;
}
declare module 'dyson/lib/util.js' {
  declare module.exports: $Exports<'dyson/lib/util'>;
}
