// flow-typed signature: dd95aa02c0ea63f23c6c4d3f24920c41
// flow-typed version: <<STUB>>/html-beautify_v^1.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-beautify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-beautify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-beautify/dist/index' {
  declare module.exports: any;
}

declare module 'html-beautify/dist/lib/html-beautify' {
  declare module.exports: any;
}

declare module 'html-beautify/src/index' {
  declare module.exports: any;
}

declare module 'html-beautify/src/lib/html-beautify' {
  declare module.exports: any;
}

declare module 'html-beautify/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-beautify/dist/index.js' {
  declare module.exports: $Exports<'html-beautify/dist/index'>;
}
declare module 'html-beautify/dist/lib/html-beautify.js' {
  declare module.exports: $Exports<'html-beautify/dist/lib/html-beautify'>;
}
declare module 'html-beautify/src/index.js' {
  declare module.exports: $Exports<'html-beautify/src/index'>;
}
declare module 'html-beautify/src/lib/html-beautify.js' {
  declare module.exports: $Exports<'html-beautify/src/lib/html-beautify'>;
}
declare module 'html-beautify/webpack.config.js' {
  declare module.exports: $Exports<'html-beautify/webpack.config'>;
}
