// flow-typed signature: 8f28ca142a710c211c81569e594bbcc7
// flow-typed version: <<STUB>>/tunnel_v0.0.6/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tunnel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tunnel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tunnel/lib/tunnel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tunnel/index' {
  declare module.exports: $Exports<'tunnel'>;
}
declare module 'tunnel/index.js' {
  declare module.exports: $Exports<'tunnel'>;
}
declare module 'tunnel/lib/tunnel.js' {
  declare module.exports: $Exports<'tunnel/lib/tunnel'>;
}
