// flow-typed signature: 41272e28fc721f53f2ca2fd9b9f64007
// flow-typed version: <<STUB>>/unirest_vlatest/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unirest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unirest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unirest/tests/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unirest/index' {
  declare module.exports: $Exports<'unirest'>;
}
declare module 'unirest/index.js' {
  declare module.exports: $Exports<'unirest'>;
}
declare module 'unirest/tests/basic.js' {
  declare module.exports: $Exports<'unirest/tests/basic'>;
}
